config/routes.rb
Rails.application.routes.draw do

  
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles

  get 'signup', to: 'users#new'
  resources :users,  except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
  validates :user_id, presence: true
end

app/models/article_category.rb
class ArticleCategory < ActiveRecord::Base
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, length: { minimum: 3, maximum: 50 }
  validates_uniqueness_of :name
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles, dependent: :destroy
  before_save { self.email = email.downcase }

  validates :username, presence: true,
                       uniqueness: { case_sensitive: false },
                       length: { minimum: 3, maximum: 25 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 },
                    uniqueness: { case_sensitive: false },
                    format: { with: VALID_EMAIL_REGEX }

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !current_user.nil?
  end

  def require_user
    if !logged_in?
      flash[:danger] = 'Você precisa realizar o login para realizar esta ação!'
      redirect_to root_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[edit show update destroy]
  before_action :require_user, except: %i[index show]
  before_action :require_same_user, only: %i[edit update destroy]

  def index
    @articles = Article.paginate(page: params[:page], per_page: 3)
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:success] = 'Artigo criado com sucesso!'
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def new
    @article = Article.new
  end

  def edit; end

  def show; end

  def update
    if @article.update(article_params)
      flash[:success] = 'Artigo atualizado com sucesso!'
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def destroy
    @article.destroy
    flash[:success] = 'Artigo removido com sucesso!'
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
    if !logged_in?
      flash[:danger] = 'Você deve realizar o login para executar esta ação!'
      redirect_to articles_path
    elsif @article.user != current_user && !current_user.admin?
      flash[:danger] = 'Você não tem permissão para editar ou remover este artigo!'
      redirect_to root_path
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: %i[index show]

  def index
    @categories = Category.paginate(page: params[:page], per_page: 3)
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Categoria \"#{@category.name}\" criada com sucesso!"
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def new
    @category = Category.new
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:success] = 'Categoria atualizada com sucesso!'
      redirect_to categories_path(@category)
    else
      render 'edit'
    end
  end

  def show
    @category = Category.find(params[:id])
    @category_articles = @category.articles.paginate(page: params[:page], per_page: 3)
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !logged_in?
      flash[:danger] = 'Você deve realizar o login e ser admin para executar esta ação!'
      redirect_to categories_path
    elsif logged_in? && !current_user.admin?
      flash[:danger] = 'Apenas usuários com perfil de administrador podem executar esta ação!'
      redirect_to categories_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end

  def about; end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "Bem vindo #{user.username}"
      redirect_to user_path(user)
    else
      flash.now[:danger] = 'Email e/ou senha inválidos!'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'Logout realizado com sucesso.'
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[edit update show]
  before_action :require_same_user, only: %i[edit update destroy]
  before_action :require_admin, only: %i[destroy]

  def index
    @users = User.paginate(page: params[:page], per_page: 3)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "#{@user.username}, sua inscrição foi realizada com sucesso. Bem vindo ao Alpha Blog!"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def edit; end

  def show
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 3)
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Usuário \"#{@user.username}\" atualizado com sucesso!"
      redirect_to articles_path(@user)
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:success] = 'Usuário removido com sucesso!'
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if !logged_in?
      flash[:danger] = 'Você deve realizar o login para executar esta ação!'
      redirect_to users_path
    elsif @user != current_user && !current_user.admin?
      flash[:danger] = 'Você não tem permissão para editar o perfil de outro usuário!'
      redirect_to users_path
    end
  end

  def require_admin
    return unless logged_in? && !current_user.admin?

    flash[:danger] = 'Apenas usuários com perfil de administrador podem executar esta ação!'
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: 'img-circle')
  end
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        <div class="article-title">
          <%= article.id %>
          <%= link_to article.title, article_path(article) %>
        </div>
        <div class="article-body">
          <%= truncate(article.description, length: 50) %>
          <div class="article-meta-details">
            <small>
              Criado por: <%= article.user.username %>, a
                          <%= time_ago_in_words(article.created_at) %>. Atualizado a
                          <%= time_ago_in_words(article.updated_at) %>
            </small>
          </div>
        </div>
        <% if article.categories.any? %>
          <p>Categorias: <%= render article.categories %></p>
        <% end %>
        <% if logged_in? && (article.user == current_user || current_user.admin?)%>
          <div class="article-actions">
            <%= link_to "Editar artigo", edit_article_path(article), class: "btn btn-xs btn-primary" %>
            <%= link_to "Remover artigo", article_path(article), class: "btn btn-xs btn-danger", method: :delete, data: {confirm: "Deseja realmente remover " + "\"" + article.title + "\"?"} %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <tr>
<% end %>

app/views/articles/_form.html.erb
<%= render "shared/errors", obj: @article %>

<div class="row">
	<div class="col-xs-12">
		<%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
			<div class="form-group">
				<div class="control-label col-sm-2">
					<%= f.label :Título %>
				</div>
				<div class="col-sm-6">
					<%= f.text_field :title, class: "form-control", placeholder: "Título do artigo", autofocus: true %>
				</div>
			</div>
			<div class="form-group">
				<div class="control-label col-sm-2">
					<%= f.label :Descrição %>
				</div>
				<div class="col-sm-10">
					<%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Descrição do artigo", autofocus: true %>
				</div>
			</div>
      <div class="form-group">
        <div class="row">
          <div class="col-sm-offset-2 col-sm-10">
            <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %> 
              <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
				  <%= f.submit class: "btn btn-primary btn-lg" %> 
        </div>
      </div>
      <div class="col-xs-6 col-xs-offset-4">
		    [ <%= link_to "Cancelar requisição e retornar para listagem de artigos", articles_path %> ]
      </div>
		<% end %>
	</div>
</div>

app/views/articles/edit.html.erb
<h1 align="center">Editar Artigo</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 align="center">Artigos</h1>

<%= render "article", obj: @articles %>
<div align="center">
	<%= will_paginate %>
</div>

app/views/articles/new.html.erb
<h1 align="center">Criar Artigo</h1>
<br><br>
<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center">Título: <%= @article.title %></h2>	
<br>
<div class="well col-xs-8 col-xs-offset-2">
  <ul class="listing">
    <div class="row center">
      <div class="col-md-4 col-md-offset-4">
        <li>Criado por:</li>
        <li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
        <li class="article-title">
          <%= link_to @article.user.username, user_path(@article.user) %>
        </li>
        <li><small><%= pluralize(@article.user.articles.count, "Artigo") if @article.user.articles %></small></li>
      </div>
    </div>
  </ul>
	<h4 class="right description"><strong>Descrição:</strong></h4>
	<%= simple_format(@article.description) %>
  <% if @article.categories.any? %>
    <h4 class="right description"><strong>Categorias: <%= render @article.categories %></strong></h4>
  <% end %>
  <div class="article-actions">
    <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
      <%= link_to "Editar artigo", edit_article_path(@article), class: "btn btn-xs btn-primary" %>
      <%= link_to "Remover artigo", article_path(@article), class: "btn btn-xs btn-danger", method: :delete, data: {confirm: "Deseja realmente remover " + "\"" + @article.title + "\"?"} %>
    <% end %>
    <%= link_to "Artigos", articles_path, class: "btn btn-xs btn-success" %>
  </div>
</div>

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category) %> &nbsp;</span> 

app/views/categories/_form.html.erb
<%= render "shared/errors", obj: @category %>

	<%= form_for(@category, :html => {class: "form-horizontal", role: "form"}) do |f| %>
		<div class="form-group">
			<div class="control-label col-sm-2">
				<%= f.label :Nome %>
			</div>
			<div class="col-sm-6">
				<%= f.text_field :name, class: "form-control", placeholder: "Nome da categoria", autofocus: true %>
			</div>
		</div>
  	<div class="form-group">
    	<div class="col-sm-offset-2 col-sm-10">
    		<%= f.submit class: "btn btn-primary btn-lg" %>
    	</div>
  	</div>
	<% end %>

app/views/categories/edit.html.erb
<h1 align="center">Editar categoria</h1>
<br><br>
<%= render 'form' %>

app/views/categories/index.html.erb
<h1 align="center">Categorias</h1>
<br><br>
<div align="center">
  <% @categories.each do |category| %>
  	<ul class="listing">
      <div class="row">
        <div class="well col-md-4 col-md-offset-4">
          <li class="article-title">
            <%= link_to "#{category.name}", category_path(category) %>
          </li>
          <li><small> <%= pluralize(category.articles.count, "Artigo") %></small></li>
        </div>
      </div>
    </ul>
  <% end %>
  <%= will_paginate %> 
</div>

app/views/categories/new.html.erb
<h1 align="center">Criar nova categoria</h1>
<br><br>
<%= render 'form' %>

app/views/categories/show.html.erb
<h1 align="center"><%= "Categoria: " + @category.name %></h1>
<% if logged_in? && current_user.admin? %>
  <div align="center">
    <div class="row">
    	<span class="badge"><%= link_to "Editar categoria", edit_category_path(@category) %></span>
    </div>
  </div>
  <br>
<% end %>
<%= render "articles/article", obj: @category_articles %>
<div align="center">
	<%= will_paginate @category_articles %>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
	<footer class="footer">
		<small>
			Copyright &copy; <a href="https://www.udemy.com">The Complete Ruby on Rails Developer</a>
			by <a href="http://www.mashrurhossain.com">Mashrur Hossain</a>
		</small>
		<nav>
			<ul>
				<li><%= link_to "Sobre", about_path %></li>
			</ul>
		</nav>
	</footer>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
	<div class="col-xs-10 col-xs-offset-1">
		<% flash.each do |name, msg| %>
      <div class='alert alert-<%="#{name}" %>'>
		    <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
		  </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Alpha Blog", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Artigos <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Ver todos", articles_path %></li>
            <% if logged_in? %>
              <li><%= link_to "Criar Artigo", new_article_path %></li>
            <% end %>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Usuários <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Ver todos", users_path %></li>
            <% if logged_in? && current_user.admin? %>
              <li><%= link_to "Criar usuário", signup_path %></li>
            <% end %>
          </ul>
        </li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categorias <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <% Category.all.each do |category| %>
                <li><%= link_to "#{category.name}", category_path(category) %></li>
              <% end %>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Ver todas", categories_path %></li>
              <% if logged_in? && current_user.admin? %>
                <li role="separator" class="divider"></li>
                <li><%= link_to "Criar Categoria", new_category_path %></li>
              <% end %>
            </ul>
      </ul>
      <!--<form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>-->
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <!--<li><%= link_to "Sair", logout_path, method: :delete %></li>-->
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Perfil <%= "Admin" if current_user.admin?  %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Ver perfil", user_path(current_user) %></li>
              <li><%= link_to "Editar perfil", edit_user_path(current_user) %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Sair", logout_path, method: :delete %></li>
              <!--<li><a href="#">Separated link</a></li>-->
            </ul>
          </li>
          <% else %>
            <li><%= link_to "Entrar", login_path %></li>
            <li><%= link_to "Cadastre-se", signup_path %></li>
          <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Alpha-Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/navigation' %>
	<%= render 'layouts/messages' %>
	<div class="container">
		<%= yield %>
	</div>
	<%= render 'layouts/footer' %>
	<%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/pages/about.html.erb
<!DOCTYPE html>
<html>
<head>
<title></title>
</head>
<body>
    <h1>Página Sobre</h1>
</body>
</html>

<%= link_to 'Home', root_path %>

app/views/pages/home.html.erb
<div class="center jumbotron">
	<h1>Alpha Blog</h1>
	<%= link_to "Entrar", login_path, class: "btn btn-info btn-lg btn-xlarge" %>
	<%= link_to "Cadastre-se", signup_path, class: "btn btn-primary btn-lg btn-xlarge" %>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
            Ação não pôde ser executada devido a 
            <%= pluralize(obj.errors.count, " erro") %>:
          </h2>
          <div class="panel-body">
          	<ul>
          		<% obj.errors.full_messages.each do |msg| %>
          		  <li><%= msg %></li>
          		<% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= render "shared/errors", obj: @user %>

<div class="row">
	<div class="col-xs-12">
		<%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
			<div class="form-group">
				<div class="control-label col-sm-2">
					<%= f.label :Nome %>
				</div>
				<div class="col-sm-6">
					<%= f.text_field :username, class: "form-control", placeholder: "Nome do usuário", autofocus: true %>
				</div>
			</div>
			<div class="form-group">
				<div class="control-label col-sm-2">
					<%= f.label :Email %>
				</div>
				<div class="col-sm-10">
					<%= f.email_field :email, class: "form-control", placeholder: "E-mail do usuário", autofocus: true %>
				</div>
			</div>
			<div class="form-group">
				<div class="control-label col-sm-2">
					<%= f.label :Senha %>
				</div>
				<div class="col-sm-10">
					<%= f.password_field :password, class: "form-control", placeholder: "Senha do usuário", autofocus: true %>
				</div>
			</div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
				  <%= link_to "Voltar", root_path, class: "btn btn-danger " %>
				  <%= f.submit(@user.new_record? ? "Inscrever-se": "Salvar alterações", class: "btn btn-primary ") %>
        </div>
      </div>
		<% end %>
	</div>
</div>

app/views/users/edit.html.erb
<h1 align="center">Editar Usuário</h1>
<br><br>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 align="center">Usuários Alpha Blog</h1>

<div align="center">
  <% @users.each do |user| %>
    <ul class="listing">
      <div class="row">
        <div class="well col-md-4 col-md-offset-4">
          <li><%= link_to gravatar_for(user), user_path(user) %></li>
          <li class="article-title">
            <%= link_to user.username, user_path(user) %>
          </li>
          <li><small><%= pluralize(user.articles.count, "Artigo") if user.articles %></small></li>
          <% if logged_in? and current_user.admin? %>
            <li><%= link_to "Excluir usuário", user_path(user), class: "btn btn-xs btn-danger", method: :delete, data: { confirm: "Deseja realmente excluir o usuário \"#{user.username}\"?"} %></li>
          <% end %>
        </div>
      </div>
    </ul>
  <% end %>
</div>
<div align="center">
  <%= will_paginate %>
</div>

app/views/users/new.html.erb
<h1 align="center">Inscreva-se no Alpha Blog</h1>
<br><br>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 align="center">Bem vindo a página de <%= @user.username %></h1>
<br>
<div class="row">
  <div class="col-md-4 col-md-offset-4 center">
    <%= gravatar_for @user, size: 150 %>
  </div>
</div>
<br>
<h4 align="center">Artigos cadastrados por <%= @user.username%></h4>
<%= render "articles/article", obj: @user_articles %>
<div class="center">
	<%= will_paginate @user_articles %>
</div>